# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3f58575b4ad9dbda03f6dbcd46d92f0b"
name = "eShipz Estimated Delivery Date"
handle = "eshipz-estimated-delivery-date"
application_url = "https://ce-accuracy-theology-uri.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "eshipz-estimated-delivery-date.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://ce-accuracy-theology-uri.trycloudflare.com/auth/callback",
  "https://ce-accuracy-theology-uri.trycloudflare.com/auth/shopify/callback",
  "https://ce-accuracy-theology-uri.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
