name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks"

[commands]
# dev = "npx prisma generate && npx prisma migrate deploy && npm exec remix vite:dev"
dev = "npx prisma generate && npx prisma db push && npm exec remix vite:dev"
